name: we_fast_driver_panel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0-180.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.0.3
  get: 4.6.1
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.8
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  location: ^4.4.0
  lottie: ^1.2.2
  sizer: ^2.0.15
  table_calendar: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/    
